export const placesSeed = [
  {
    name: "Menega Cafe",
    category: "restaurant",
    description: "Seafood restaurant populer di area Pantai Jimbaran.",
    address: "Jl. Four Seasons Muaya Beach, Jimbaran, Bali",
    latitude: -8.783289,
    longitude: 115.163694,
    opening_hours: "11.00 - 23.00",
    phone: "+62 361 705888",
    rating: 4.4,
    price_level: 3,
    is_halal: false,
    is_featured: true,
    marker_icon: "restaurant",
  },
  {
    name: "Cuca Restaurant",
    category: "restaurant",
    description: "Restaurant casual fine dining dengan menu tapas dan dessert.",
    address: "Jl. Yoga Perkanthi, Jimbaran, Bali",
    latitude: -8.779401,
    longitude: 115.168342,
    opening_hours: "12.00 - 23.00",
    phone: "+62 812 3687 0486",
    rating: 4.7,
    price_level: 4,
    is_halal: false,
    is_featured: true,
    marker_icon: "restaurant",
  },
  {
    name: "Sundara Beach Club",
    category: "restaurant",
    description: "Beachfront dining dan lounge di kawasan Four Seasons Jimbaran.",
    address: "Four Seasons Resort Bali at Jimbaran Bay, Jimbaran, Bali",
    latitude: -8.783948,
    longitude: 115.161882,
    opening_hours: "11.00 - 23.00",
    phone: "+62 361 708333",
    rating: 4.6,
    price_level: 4,
    is_halal: false,
    is_featured: true,
    marker_icon: "restaurant",
  },
  {
    name: "Bawang Merah Beachfront Jimbaran",
    category: "restaurant",
    description: "Restaurant seafood tepi pantai di kawasan Kedonganan-Jimbaran.",
    address: "Jl. Pantai Kedonganan, Kedonganan, Bali",
    latitude: -8.759937,
    longitude: 115.168508,
    opening_hours: "11.00 - 23.00",
    phone: "+62 361 770210",
    rating: 4.3,
    price_level: 3,
    is_halal: false,
    is_featured: false,
    marker_icon: "restaurant",
  },
  {
    name: "Kayumanis Resto Jimbaran",
    category: "restaurant",
    description: "Restaurant Indonesia dengan suasana tropis di Jimbaran.",
    address: "Jl. Yoga Perkanthi, Jimbaran, Bali",
    latitude: -8.778801,
    longitude: 115.168961,
    opening_hours: "07.00 - 23.00",
    phone: "+62 361 705777",
    rating: 4.6,
    price_level: 3,
    is_halal: true,
    is_featured: false,
    marker_icon: "restaurant",
  },
  {
    name: "Tarabelle Donuts Coffee & Eats Jimbaran",
    category: "cafe",
    description: "Cafe dengan menu donat, kopi, dan makanan ringan.",
    address: "Jimbaran, Kuta Selatan, Badung, Bali",
    latitude: -8.785017,
    longitude: 115.177328,
    opening_hours: "08.00 - 22.00",
    phone: "",
    rating: 4.5,
    price_level: 2,
    is_halal: true,
    is_featured: false,
    marker_icon: "cafe",
  },
  {
    name: "Koffietons Jimbaran",
    category: "cafe",
    description: "Cafe lokal untuk kopi, brunch, dan tempat santai.",
    address: "Jl. Uluwatu II, Jimbaran, Bali",
    latitude: -8.793052,
    longitude: 115.181737,
    opening_hours: "08.00 - 22.00",
    phone: "",
    rating: 4.5,
    price_level: 2,
    is_halal: true,
    is_featured: false,
    marker_icon: "cafe",
  },
  {
    name: "70 Fahrenheit Koffie Jimbaran",
    category: "cafe",
    description: "Cafe modern dengan pilihan kopi dan makanan ringan.",
    address: "Jimbaran, Kuta Selatan, Badung, Bali",
    latitude: -8.790199,
    longitude: 115.176923,
    opening_hours: "08.00 - 22.00",
    phone: "",
    rating: 4.4,
    price_level: 2,
    is_halal: true,
    is_featured: false,
    marker_icon: "cafe",
  },
  {
    name: "Starbucks Jimbaran Sidewalk",
    category: "coffee_shop",
    description: "Coffee shop jaringan internasional di area Jimbaran Sidewalk.",
    address: "Jimbaran Sidewalk, Jl. Raya Uluwatu, Jimbaran, Bali",
    latitude: -8.799052,
    longitude: 115.161459,
    opening_hours: "08.00 - 22.00",
    phone: "",
    rating: 4.5,
    price_level: 3,
    is_halal: true,
    is_featured: false,
    marker_icon: "coffee_shop",
  },
  {
    name: "Expat. Roasters Jimbaran",
    category: "coffee_shop",
    description: "Coffee shop specialty dengan menu kopi dan pastry.",
    address: "Jimbaran, Kuta Selatan, Badung, Bali",
    latitude: -8.798533,
    longitude: 115.160817,
    opening_hours: "07.00 - 21.00",
    phone: "",
    rating: 4.6,
    price_level: 3,
    is_halal: true,
    is_featured: false,
    marker_icon: "coffee_shop",
  },
  {
    name: "Daily Baguette Jimbaran",
    category: "bakery",
    description: "Bakery dengan pilihan roti, pastry, dan kopi.",
    address: "Jimbaran, Kuta Selatan, Badung, Bali",
    latitude: -8.792724,
    longitude: 115.177878,
    opening_hours: "07.00 - 21.00",
    phone: "",
    rating: 4.5,
    price_level: 2,
    is_halal: true,
    is_featured: false,
    marker_icon: "bakery",
  },
  {
    name: "BreadTalk Samasta Jimbaran",
    category: "bakery",
    description: "Bakery modern di area Samasta Lifestyle Village.",
    address: "Samasta Lifestyle Village, Jimbaran, Bali",
    latitude: -8.787526,
    longitude: 115.169482,
    opening_hours: "10.00 - 22.00",
    phone: "",
    rating: 4.3,
    price_level: 2,
    is_halal: true,
    is_featured: false,
    marker_icon: "bakery",
  },
  {
    name: "McDonald's Jimbaran",
    category: "fast_food_restaurant",
    description: "Fast food restaurant dengan menu burger, ayam, dan minuman.",
    address: "Jl. By Pass Ngurah Rai, Jimbaran, Bali",
    latitude: -8.783806,
    longitude: 115.183802,
    opening_hours: "24 jam",
    phone: "14045",
    rating: 4.4,
    price_level: 2,
    is_halal: true,
    is_featured: false,
    marker_icon: "fast_food_restaurant",
  },
  {
    name: "KFC Jimbaran",
    category: "fast_food_restaurant",
    description: "Fast food restaurant ayam goreng di kawasan Jimbaran.",
    address: "Jl. By Pass Ngurah Rai, Jimbaran, Bali",
    latitude: -8.785571,
    longitude: 115.184747,
    opening_hours: "10.00 - 22.00",
    phone: "14022",
    rating: 4.3,
    price_level: 2,
    is_halal: true,
    is_featured: false,
    marker_icon: "fast_food_restaurant",
  },
  {
    name: "Burger King Jimbaran",
    category: "fast_food_restaurant",
    description: "Fast food restaurant dengan menu burger dan kentang goreng.",
    address: "Jimbaran, Kuta Selatan, Badung, Bali",
    latitude: -8.787233,
    longitude: 115.183151,
    opening_hours: "10.00 - 22.00",
    phone: "",
    rating: 4.3,
    price_level: 2,
    is_halal: true,
    is_featured: false,
    marker_icon: "fast_food_restaurant",
  },
  {
    name: "Pizza Hut Delivery Jimbaran",
    category: "meal_takeaway",
    description: "Outlet takeaway dan delivery pizza di area Jimbaran.",
    address: "Jl. Raya Uluwatu, Jimbaran, Bali",
    latitude: -8.790786,
    longitude: 115.177319,
    opening_hours: "10.00 - 22.00",
    phone: "1500600",
    rating: 4.3,
    price_level: 2,
    is_halal: true,
    is_featured: false,
    marker_icon: "meal_takeaway",
  },
  {
    name: "Domino's Pizza Jimbaran",
    category: "meal_takeaway",
    description: "Outlet pizza untuk takeaway dan delivery.",
    address: "Jimbaran, Kuta Selatan, Badung, Bali",
    latitude: -8.791599,
    longitude: 115.178087,
    opening_hours: "10.00 - 22.00",
    phone: "1500366",
    rating: 4.3,
    price_level: 2,
    is_halal: true,
    is_featured: false,
    marker_icon: "meal_takeaway",
  },
  {
    name: "Warung Nasi Ayam Bu Oki Jimbaran",
    category: "meal_takeaway",
    description: "Warung nasi ayam Bali yang populer untuk makan di tempat maupun bungkus.",
    address: "Jl. Celagi Basur, Jimbaran, Bali",
    latitude: -8.790285,
    longitude: 115.177186,
    opening_hours: "08.00 - 20.00",
    phone: "",
    rating: 4.5,
    price_level: 1,
    is_halal: false,
    is_featured: true,
    marker_icon: "meal_takeaway",
  },
  {
    name: "Gaya Gelato Jimbaran",
    category: "ice_cream_shop",
    description: "Gelato shop dengan berbagai pilihan rasa es krim.",
    address: "Jimbaran, Kuta Selatan, Badung, Bali",
    latitude: -8.789108,
    longitude: 115.169177,
    opening_hours: "10.00 - 22.00",
    phone: "",
    rating: 4.5,
    price_level: 2,
    is_halal: true,
    is_featured: false,
    marker_icon: "ice_cream_shop",
  },
  {
    name: "Gelato Secrets Uluwatu",
    category: "ice_cream_shop",
    description: "Gelato dan sorbet dengan pilihan rasa khas tropis.",
    address: "Jl. Labuansait, Pecatu, Bali",
    latitude: -8.811653,
    longitude: 115.114332,
    opening_hours: "10.00 - 22.00",
    phone: "",
    rating: 4.5,
    price_level: 2,
    is_halal: true,
    is_featured: false,
    marker_icon: "ice_cream_shop",
  },
];
